### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rmatsum836** [rmatsum836/water_vhf_analysis#4]
- [ ] Test partial functions
- [x] Test that form factors are accurate
- [ ] Add `environment.yml` file
